'use strict';

// Español e inglés. La jerga de Pío no se traduce: pío, piar, nido, plaza,
// repío y pollito son la marca, y quedan igual en los dos idiomas. Lo que se
// traduce es todo lo que las rodea.
//
// Un valor puede ser texto o una función que recibe datos, para los casos que
// llevan un número o un nombre adentro.

window.IDIOMAS = {
  es: {
    nombre: 'Español',
    etiqueta: 'ES',
    fechas: 'es',
    textos: {
      'titulo': 'Pío — 100 caracteres y listo',
      'portada.lema1': 'Cien caracteres. Ni uno más.',
      'portada.lema2': 'Si no entra, no era tan importante.',
      'portada.local': 'Todo se guarda en tu propia máquina, en <code>datos/pio.json</code>.',
      'acceso.entrar': 'Entrar',
      'acceso.crear': 'Crear pollito',
      'acceso.o': 'o',
      'acceso.olvide': '¿Olvidaste tu clave?',
      'acceso.volver': 'Volver a entrar',
      'acceso.boton.recuperar': 'Recuperar mi cuenta',
      'codigo.titulo': 'Tu código de recuperación',
      'codigo.explica': 'Es la única forma de volver a entrar si olvidas tu clave. No lo vamos a mostrar de nuevo.',
      'codigo.viejo': 'Tu cuenta es de antes de que existieran estos códigos. Aquí está el tuyo.',
      'codigo.aviso': 'Guárdalo donde no se pierda. Quien lo tenga puede entrar a tu cuenta.',
      'codigo.copiar': 'Copiar',
      'codigo.copiado': 'Copiado',
      'codigo.guardado': 'Ya lo guardé',
      'codigo.pedirOtro': 'Cambiar el código',
      'codigo.nuevo': 'Código nuevo. El anterior ya no sirve.',
      'clave.titulo': 'Cambiar la clave',
      'clave.actual': 'Tu clave actual',
      'clave.nueva': 'La nueva',
      'clave.guardar': 'Cambiar',
      'clave.lista': 'Clave cambiada. Las otras sesiones se cerraron.',
      'perfil.clave': 'Cambiar clave',
      'acceso.boton.entrar': 'Entrar al nido',
      'acceso.boton.crear': 'Crear mi pollito',
      'campo.usuario': 'Usuario',
      'campo.nombre': 'Nombre para mostrar',
      'campo.clave': 'Clave',
      'campo.clave.ph': 'mínimo 6 caracteres',
      'campo.codigo': 'Código de recuperación',
      'campo.codigo.ph': 'PIO-XXXXX-XXXXX-XXXXX',
      'campo.bio': 'Sobre ti',
      'campo.bio.ph': 'cien caracteres, como todo aquí',

      'nav.nido': 'Nido',
      'nav.plaza': 'Plaza',
      'nav.avisos': 'Avisos',
      'nav.buscar': 'Buscar',
      'nav.perfil': 'Mi perfil',
      'nav.tema': 'Tema',
      'nav.idioma': 'Idioma',
      'nav.disenos': 'Diseños',
      'boton.piar': 'Piar',
      'barra.volver': 'Volver',
      'barra.tema': 'Cambiar tema',
      'barra.idioma': 'Cambiar idioma',

      'lateral.tendencias': 'Tendencias del gallinero',
      'lateral.seguir': 'A quién seguir',
      'lateral.pie': 'Pío · 100 caracteres · hecho en casa',
      'tendencias.vacio': 'Todavía nadie usó etiquetas. Prueba con #pio.',
      'tendencia.pios': (d) => `${d.n} pío${d.n === 1 ? '' : 's'}`,
      'sugerencias.vacio': 'Cuando haya más pollitos, aparecen aquí.',
      'sugerencias.todos': 'Ya sigues a todo el gallinero. 🐔',

      'cargando': 'Piando… 🐤',
      'nido.titulo': 'Tu nido',
      'nido.sub': 'Tú y quienes sigues',
      'nido.vacio': 'Tu nido está callado. Sigue a alguien en la Plaza, o pía tú.',
      'plaza.titulo': 'La plaza',
      'plaza.sub': 'Todo lo que pía el gallinero',
      'plaza.vacio': 'Nadie ha piado todavía. Estrena la plaza.',
      'etiqueta.sub': 'Píos con esta etiqueta',
      'etiqueta.vacio': 'Nada con esa etiqueta… todavía.',
      'buscar.titulo': 'Buscar',
      'buscar.ph': 'Busca píos, etiquetas o pollitos',
      'buscar.empezar': 'Escribe algo y vemos qué aparece.',
      'buscar.pollitos': 'Pollitos',
      'buscar.vacio': 'Ningún pío coincide.',
      'hilo.titulo': 'Pío',
      'hilo.sub': 'El hilo completo',
      'hilo.vacio': 'Sin respuestas. Contesta tú.',
      'hilo.plegar': 'Plegar esta rama',
      'hilo.desplegar': 'Desplegar esta rama',
      'hilo.ocultas': (d) => `${d.n} respuesta${d.n === 1 ? '' : 's'} oculta${d.n === 1 ? '' : 's'}`,
      'hilo.recortado': 'El hilo sigue, pero hasta aquí llega lo que mostramos.',
      'avisos.titulo': 'Avisos',
      'avisos.sub': 'Quién ha estado piándote',
      'avisos.vacio': 'Ningún aviso todavía. Pía algo y espera.',
      'disenos.titulo': 'Diseños',
      'disenos.sub': 'Diez propuestas, todas funcionando. Elige la que quieras.',
      'disenos.usar': 'Usar',
      'disenos.enUso': 'En uso',
      'disenos.base.nombre': 'Original',
      'disenos.base.que': 'El diseño con el que nació el sitio.',

      'perfil.pios': (d) => `${d.n} pío${d.n === 1 ? '' : 's'}`,
      'perfil.siguiendo': 'siguiendo',
      'perfil.seguidores': 'seguidores',
      'perfil.desde': (d) => `en el gallinero desde ${d.fecha}`,
      'perfil.salir': 'Cerrar sesión',
      'perfil.seguir': 'Seguir',
      'perfil.siguiendoYa': 'Siguiendo',
      'medalla.huevo': 'Huevo',
      'medalla.cascaron': 'Rompiendo el cascarón',
      'medalla.pollito': 'Pollito',
      'medalla.gallo': 'Gallo',
      'medalla.pato': 'Pato',
      'medalla.cisne': 'Cisne',
      'medalla.buho': 'Búho',
      'medalla.aguila': 'Águila',
      'medalla.pavoreal': 'Pavo real',
      'medalla.detalle': (d) => `${d.nombre} · ${d.desde} seguidores`,
      'medalla.proxima': (d) => `${d.faltan} para ${d.nombre}`,
      'perfil.solapa.pios': 'Píos',
      'perfil.solapa.megusta': 'Me gusta',
      'perfil.vacio.pios': 'Ni un pío por aquí.',
      'perfil.vacio.megusta': 'Todavía no le gustó nada.',

      'pio.repiadoPor': (d) => `🔁 repiado por @${d.usuario}`,
      'pio.respuestaA': '💬 en respuesta a un pío',
      'accion.responder': 'Responder',
      'accion.repiar': 'Repiar',
      'accion.megusta': 'Me gusta',
      'accion.borrar': 'Borrar',

      'dialogo.nuevo': 'Nuevo pío',
      'dialogo.respuesta': 'Tu respuesta',
      'dialogo.contexto': 'Respondiendo a un pío del gallinero',
      'dialogo.ph': '¿Qué estás piando?',
      'dialogo.aria': 'Texto del pío',
      'dialogo.cerrar': 'Cerrar',
      'adjunto.imagen': 'Poner una imagen',
      'adjunto.gif': 'Buscar un GIF',
      'adjunto.quitar': 'Quitar',
      'adjunto.alt': 'Describe la imagen para quien no la ve',
      'adjunto.subiendo': 'Subiendo…',
      'adjunto.pesada': 'Esa imagen pesa demasiado. El tope son 5 MB.',
      'gif.ph': 'Busca un GIF',
      'enlace.acortar': 'Acortar las direcciones del pío',
      'enlace.ninguna': 'No hay ninguna dirección para acortar.',
      'enlace.acortando': 'Acortando…',
      'enlace.listo': (d) => `${d.n} dirección${d.n === 1 ? '' : 'es'} acortada${d.n === 1 ? '' : 's'}`,
      'gif.vacio': 'Nada con esa búsqueda.',
      'perfil.editar': 'Editar perfil',
      'perfil.guardar': 'Guardar',
      'perfil.guardado': 'Perfil guardado 🐤',
      'perfil.usuarioEspera': 'El nombre de usuario se puede cambiar una vez cada treinta días.',
      'perfil.usuarioTrabado': 'Lo cambiaste hace poco. Vas a poder de nuevo más adelante.',

      'aviso.mencion': 'te mencionó',
      'aviso.respuesta': 'te respondió',
      'aviso.repio': 'repió tu pío',
      'aviso.megusta': 'le gustó tu pío',
      'aviso.seguir': 'te empezó a seguir',
      'aviso.otro': 'anduvo por aquí',

      'toast.nidoCreado': '¡Pollito creado! 🐣',
      'toast.bienvenida': '¡Bienvenido de vuelta! 🐤',
      'toast.pio': '¡Pío! 🐤',
      'toast.respuesta': 'Respuesta enviada 🐤',
      'toast.borrado': 'Pío borrado.',
      'toast.sigue': (d) => `Ahora sigues a @${d.usuario}`,
      'toast.noSigue': (d) => `Dejaste de seguir a @${d.usuario}`,
      'toast.vencio': 'Tu sesión venció. Entra de nuevo.',
      'confirmar.borrar': '¿Borrar este pío para siempre?',
      'error.generico': 'Algo salió mal.',
    },
    errores: {
      'usuario.corto': 'El usuario necesita al menos 3 caracteres.',
      'usuario.falta': 'Elige un nombre de usuario.',
      'usuario.forma': (d) => `El usuario va de ${d.min} a ${d.max} caracteres: minúsculas, números y _.`,
      'usuario.sinlugar': 'No quedan nombres libres parecidos a ese.',
      'nombre.falta': 'Pon un nombre para mostrar.',
      'nombre.largo': (d) => `El nombre no puede pasar de ${d.limite} caracteres.`,
      'clave.corta': (d) => `La clave necesita al menos ${d.minimo} caracteres.`,
      'clave.larga': 'Esa clave es demasiado larga.',
      'pio.vacio': 'Un pío vacío no es un pío.',
      'pio.largo': (d) => `Te pasaste por ${d.sobra}. El límite es ${d.limite}.`,
      'pio.noesta': 'Ese pío ya no está.',
      'pio.ajeno': 'Solo puedes borrar tus propios píos.',
      'bio.larga': (d) => `La bio tampoco pasa de ${d.limite} caracteres.`,
      'usuario.ocupado': 'Ya hay un pollito con ese nombre.',
      'usuario.reservado': 'Ese nombre está guardado para el sitio. Elige otro.',
      'pollito.noexiste': 'No existe ese pollito.',
      'seguir.vosmismo': 'No puedes seguirte a ti mismo.',
      'repio.propio': 'Repiar lo tuyo es hacer trampa.',
      'acceso.malo': 'Usuario o clave incorrectos.',
      'sesion.falta': 'Entra a tu nido primero.',
      'cuerpo.malo': 'El cuerpo no es JSON válido.',
      'ruta.desconocida': 'Ruta desconocida.',
      'altas.muchas': (d) => `Demasiadas cuentas nuevas desde aquí. Intenta en ${d.minutos} minuto${d.minutos === 1 ? '' : 's'}.`,
      'google.apagado': 'Este Pío no tiene configurado el acceso con Google.',
      'google.malo': 'Google no validó esa entrada.',
      'enlace.malo': 'Eso no es una dirección que se pueda acortar.',
      'enlace.rechazado': 'El acortador no la aceptó.',
      'enlace.raro': 'El acortador devolvió una dirección que no es de fiar.',
      'enlace.apagado': 'Este Pío tiene apagado el acortador.',
      'codigo.malo': 'Ese usuario y ese código no coinciden.',
      'clave.actualmala': 'Esa no es tu clave actual.',
      'intentos.muchos': (d) => `Demasiados intentos desde aquí. Intenta en ${d.minutos} minuto${d.minutos === 1 ? '' : 's'}.`,
      'interno': 'Se nos cayó el nido. Intenta de nuevo.',
    },
  },

  en: {
    nombre: 'English',
    etiqueta: 'EN',
    fechas: 'en',
    textos: {
      'titulo': 'Pío — 100 characters and done',
      'portada.lema1': 'One hundred characters. Not one more.',
      'portada.lema2': 'If it does not fit, it was not that important.',
      'portada.local': 'Everything is saved on your own machine, in <code>datos/pio.json</code>.',
      'acceso.entrar': 'Sign in',
      'acceso.crear': 'Create pollito',
      'acceso.o': 'or',
      'acceso.olvide': 'Forgot your password?',
      'acceso.volver': 'Back to sign in',
      'acceso.boton.recuperar': 'Recover my account',
      'codigo.titulo': 'Your recovery code',
      'codigo.explica': 'It is the only way back in if you forget your password. We will not show it again.',
      'codigo.viejo': 'Your account predates these codes. Here is yours.',
      'codigo.aviso': 'Keep it somewhere safe. Whoever has it can get into your account.',
      'codigo.copiar': 'Copy',
      'codigo.copiado': 'Copied',
      'codigo.guardado': 'Saved it',
      'codigo.pedirOtro': 'Change the code',
      'codigo.nuevo': 'New code. The old one no longer works.',
      'clave.titulo': 'Change password',
      'clave.actual': 'Your current password',
      'clave.nueva': 'The new one',
      'clave.guardar': 'Change',
      'clave.lista': 'Password changed. Other sessions were closed.',
      'perfil.clave': 'Change password',
      'acceso.boton.entrar': 'Enter your nido',
      'acceso.boton.crear': 'Create my pollito',
      'campo.usuario': 'Username',
      'campo.nombre': 'Display name',
      'campo.clave': 'Password',
      'campo.clave.ph': 'at least 6 characters',
      'campo.codigo': 'Recovery code',
      'campo.codigo.ph': 'PIO-XXXXX-XXXXX-XXXXX',
      'campo.bio': 'About you',
      'campo.bio.ph': 'a hundred characters, like everything here',

      'nav.nido': 'Nido',
      'nav.plaza': 'Plaza',
      'nav.avisos': 'Notifications',
      'nav.buscar': 'Search',
      'nav.perfil': 'My profile',
      'nav.tema': 'Theme',
      'nav.idioma': 'Language',
      'nav.disenos': 'Designs',
      'boton.piar': 'Piar',
      'barra.volver': 'Back',
      'barra.tema': 'Switch theme',
      'barra.idioma': 'Switch language',

      'lateral.tendencias': 'Trending in the coop',
      'lateral.seguir': 'Who to follow',
      'lateral.pie': 'Pío · 100 characters · homemade',
      'tendencias.vacio': 'No tags yet. Try #pio.',
      'tendencia.pios': (d) => `${d.n} pío${d.n === 1 ? '' : 's'}`,
      'sugerencias.vacio': 'When there are more pollitos, they show up here.',
      'sugerencias.todos': 'You already follow the whole coop. 🐔',

      'cargando': 'Piando… 🐤',
      'nido.titulo': 'Your nido',
      'nido.sub': 'You and the pollitos you follow',
      'nido.vacio': 'Your nido is quiet. Follow someone in the Plaza, or pía something yourself.',
      'plaza.titulo': 'The plaza',
      'plaza.sub': 'Everything the coop is piando',
      'plaza.vacio': 'Nobody has piado yet. Break in the plaza.',
      'etiqueta.sub': 'Píos with this tag',
      'etiqueta.vacio': 'Nothing with that tag… yet.',
      'buscar.titulo': 'Search',
      'buscar.ph': 'Search píos, tags or pollitos',
      'buscar.empezar': 'Type something and we will see what shows up.',
      'buscar.pollitos': 'Pollitos',
      'buscar.vacio': 'No pío matches.',
      'hilo.titulo': 'Pío',
      'hilo.sub': 'The full thread',
      'hilo.vacio': 'No replies. Be the first.',
      'hilo.plegar': 'Collapse this branch',
      'hilo.desplegar': 'Expand this branch',
      'hilo.ocultas': (d) => `${d.n} ${d.n === 1 ? 'reply' : 'replies'} hidden`,
      'hilo.recortado': 'The thread goes on, but this is as far as we show.',
      'avisos.titulo': 'Notifications',
      'avisos.sub': 'Who has been piando at you',
      'avisos.vacio': 'Nothing yet. Pía something and wait.',
      'disenos.titulo': 'Designs',
      'disenos.sub': 'Ten proposals, all working. Pick whichever you like.',
      'disenos.usar': 'Use',
      'disenos.enUso': 'In use',
      'disenos.base.nombre': 'Original',
      'disenos.base.que': 'The design the site was born with.',

      'perfil.pios': (d) => `${d.n} pío${d.n === 1 ? '' : 's'}`,
      'perfil.siguiendo': 'following',
      'perfil.seguidores': 'followers',
      'perfil.desde': (d) => `in the coop since ${d.fecha}`,
      'perfil.salir': 'Sign out',
      'perfil.seguir': 'Follow',
      'perfil.siguiendoYa': 'Following',
      'medalla.huevo': 'Huevo',
      'medalla.cascaron': 'Rompiendo el cascarón',
      'medalla.pollito': 'Pollito',
      'medalla.gallo': 'Gallo',
      'medalla.pato': 'Pato',
      'medalla.cisne': 'Cisne',
      'medalla.buho': 'Búho',
      'medalla.aguila': 'Águila',
      'medalla.pavoreal': 'Pavo real',
      'medalla.detalle': (d) => `${d.nombre} · ${d.desde} seguidores`,
      'medalla.proxima': (d) => `${d.faltan} para ${d.nombre}`,
      'medalla.huevo': 'Egg',
      'medalla.cascaron': 'Breaking the shell',
      'medalla.pollito': 'Pollito',
      'medalla.gallo': 'Rooster',
      'medalla.pato': 'Duck',
      'medalla.cisne': 'Swan',
      'medalla.buho': 'Owl',
      'medalla.aguila': 'Eagle',
      'medalla.pavoreal': 'Peacock',
      'medalla.detalle': (d) => `${d.nombre} · ${d.desde} followers`,
      'medalla.proxima': (d) => `${d.faltan} to go for ${d.nombre}`,
      'perfil.solapa.pios': 'Píos',
      'perfil.solapa.megusta': 'Likes',
      'perfil.vacio.pios': 'Not a single pío here.',
      'perfil.vacio.megusta': 'Has not liked anything yet.',

      'pio.repiadoPor': (d) => `🔁 repiado by @${d.usuario}`,
      'pio.respuestaA': '💬 replying to a pío',
      'accion.responder': 'Reply',
      'accion.repiar': 'Repiar',
      'accion.megusta': 'Like',
      'accion.borrar': 'Delete',

      'dialogo.nuevo': 'New pío',
      'dialogo.respuesta': 'Your reply',
      'dialogo.contexto': 'Replying to a pío from the coop',
      'dialogo.ph': 'What are you piando?',
      'dialogo.aria': 'Pío text',
      'dialogo.cerrar': 'Close',
      'adjunto.imagen': 'Add an image',
      'adjunto.gif': 'Find a GIF',
      'adjunto.quitar': 'Remove',
      'adjunto.alt': 'Describe the image for those who cannot see it',
      'adjunto.subiendo': 'Uploading…',
      'adjunto.pesada': 'That image is too heavy. The limit is 5 MB.',
      'gif.ph': 'Search for a GIF',
      'enlace.acortar': 'Shorten the links in this pío',
      'enlace.ninguna': 'There is no link to shorten.',
      'enlace.acortando': 'Shortening…',
      'enlace.listo': (d) => `${d.n} link${d.n === 1 ? '' : 's'} shortened`,
      'gif.vacio': 'Nothing for that search.',
      'perfil.editar': 'Edit profile',
      'perfil.guardar': 'Save',
      'perfil.guardado': 'Profile saved 🐤',
      'perfil.usuarioEspera': 'The username can be changed once every thirty days.',
      'perfil.usuarioTrabado': 'You changed it recently. You will be able to again later.',

      'aviso.mencion': 'mentioned you',
      'aviso.respuesta': 'replied to you',
      'aviso.repio': 'repió your pío',
      'aviso.megusta': 'liked your pío',
      'aviso.seguir': 'started following you',
      'aviso.otro': 'was around',

      'toast.nidoCreado': 'Pollito created! 🐣',
      'toast.bienvenida': 'Welcome back! 🐤',
      'toast.pio': '¡Pío! 🐤',
      'toast.respuesta': 'Reply sent 🐤',
      'toast.borrado': 'Pío deleted.',
      'toast.sigue': (d) => `You now follow @${d.usuario}`,
      'toast.noSigue': (d) => `You unfollowed @${d.usuario}`,
      'toast.vencio': 'Your session expired. Sign in again.',
      'confirmar.borrar': 'Delete this pío forever?',
      'error.generico': 'Something went wrong.',
    },
    errores: {
      'usuario.corto': 'The username needs at least 3 characters.',
      'usuario.falta': 'Pick a username.',
      'usuario.forma': (d) => `Usernames run ${d.min} to ${d.max} characters: lowercase, digits and _.`,
      'usuario.sinlugar': 'No names like that one are left.',
      'nombre.falta': 'Enter a display name.',
      'nombre.largo': (d) => `The name cannot go past ${d.limite} characters.`,
      'clave.corta': (d) => `The password needs at least ${d.minimo} characters.`,
      'clave.larga': 'That password is too long.',
      'pio.vacio': 'An empty pío is not a pío.',
      'pio.largo': (d) => `You went over by ${d.sobra}. The limit is ${d.limite}.`,
      'pio.noesta': 'That pío is gone.',
      'pio.ajeno': 'You can only delete your own píos.',
      'bio.larga': (d) => `The bio does not go past ${d.limite} characters either.`,
      'usuario.ocupado': 'There is already a pollito with that name.',
      'usuario.reservado': 'That name is reserved for the site. Pick another.',
      'pollito.noexiste': 'No such pollito.',
      'seguir.vosmismo': 'You cannot follow yourself.',
      'repio.propio': 'Repiar your own is cheating.',
      'acceso.malo': 'Wrong username or password.',
      'sesion.falta': 'Enter your nido first.',
      'cuerpo.malo': 'That body is not valid JSON.',
      'ruta.desconocida': 'Unknown route.',
      'altas.muchas': (d) => `Too many new accounts from here. Try again in ${d.minutos} minute${d.minutos === 1 ? '' : 's'}.`,
      'google.apagado': 'This Pío does not have Google sign-in configured.',
      'google.malo': 'Google did not validate that sign-in.',
      'enlace.malo': 'That is not a link that can be shortened.',
      'enlace.rechazado': 'The shortener did not accept it.',
      'enlace.raro': 'The shortener returned a link that cannot be trusted.',
      'enlace.apagado': 'This Pío has the shortener turned off.',
      'codigo.malo': 'That username and code do not match.',
      'clave.actualmala': 'That is not your current password.',
      'intentos.muchos': (d) => `Too many attempts from here. Try again in ${d.minutos} minute${d.minutos === 1 ? '' : 's'}.`,
      'interno': 'The nido fell down. Try again.',
    },
  },
};
